---
abstract: 'Calculate similarity of the vertices in graph(s)'
author:
  - 'Shohei Kameda <shoheik@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Similarity
provides:
  Graph::Similarity:
    file: lib/Graph/Similarity.pm
    version: v0.0.2
  Graph::Similarity::CoupledNodeEdgeScoring:
    file: lib/Graph/Similarity/CoupledNodeEdgeScoring.pm
    version: v0.0.2
  Graph::Similarity::Method:
    file: lib/Graph/Similarity/Method.pm
    version: v0.0.1
  Graph::Similarity::SimRank:
    file: lib/Graph/Similarity/SimRank.pm
    version: v0.0.2
  Graph::Similarity::SimilarityFlooding:
    file: lib/Graph/Similarity/SimilarityFlooding.pm
    version: v0.0.2
requires:
  Graph: 0
  Math::Matrix: 0
  Moose: 0
  Moose::Role: 0
  Test::Exception: 0
  Test::More: 0
  Test::Output: 0
  Text::Levenshtein: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.2
